export function ownerPage() {
  const nonce = [...crypto.getRandomValues(new Uint8Array(16))].map(x => x.toString(16).padStart(2, '0')).join('');
  return new Response(`<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>مدیریت Venzo</title>
<style nonce="${nonce}">
:root{color-scheme:dark;--bg:#090b10;--card:#141820;--line:#303644;--muted:#b3bac8;--red:#e92142}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:#f5f6fa;font:16px/1.8 Tahoma,Arial,sans-serif}button,input,textarea,select{font:inherit}button{cursor:pointer;background:#292f3b;color:#fff;border:1px solid #454d5e;border-radius:10px;padding:9px 15px;min-height:44px}button:disabled{opacity:.5;cursor:wait}button.primary{background:var(--red);border-color:var(--red)}button.danger{color:#ffbbc6;border-color:#c53c54}button:focus-visible,input:focus,textarea:focus,select:focus{outline:2px solid #ff879b;outline-offset:2px}input,textarea,select{width:100%;background:#0b0f15;border:1px solid #454d5e;border-radius:9px;color:#fff;padding:10px}textarea{min-height:180px}label{display:grid;gap:6px;margin:12px 0}input[type=checkbox]{width:auto}h1{font-size:26px;margin:0}h2{font-size:20px;margin:0 0 12px}p{margin:8px 0}.hidden,[hidden]{display:none!important}.muted,small{color:var(--muted)}small{font-size:14px}.ltr{direction:ltr;text-align:left}.login{max-width:430px;margin:12vh auto;padding:26px}.card{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:20px}.shell{max-width:1320px;margin:auto;padding:24px}.top,.row{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.nav{display:flex;gap:8px;flex-wrap:wrap;margin:22px 0}.nav button.active{background:#76132b;border-color:#ff6a86}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.split{display:grid;grid-template-columns:1fr 1fr;gap:16px}.metric strong{display:block;font-size:30px}.section{margin:16px 0}.table{overflow:auto}table{border-collapse:collapse;width:100%;min-width:500px}th,td{text-align:right;border-bottom:1px solid var(--line);padding:12px;font-size:14px}th{color:var(--muted)}.note{background:#221d15;border:1px solid #826135;border-radius:10px;padding:12px}.message{position:sticky;top:0;z-index:5;background:#25151d;color:#ffd4dc;padding:12px;border:1px solid #bd536b;margin:12px 0;border-radius:10px}.list{display:grid;gap:12px}.good{color:#80dfbc}.bad{color:#ff9baa}.pill{display:inline-block;padding:3px 9px;border:1px solid #454d5e;border-radius:99px;font-size:14px}.draft{border-right:4px solid #ffb454;padding-right:12px}.barline{display:flex;gap:8px;align-items:center;direction:ltr}.barline meter{flex:1;width:100%;height:20px}.tools{display:flex;gap:8px;flex-wrap:wrap}a{color:#ffa8b8}.empty{padding:22px;text-align:center;color:var(--muted)}@media(max-width:850px){.grid{grid-template-columns:repeat(2,1fr)}.split{grid-template-columns:1fr}.shell{padding:14px}}@media(max-width:460px){.grid{grid-template-columns:1fr}.card{padding:14px}.login{margin:6vh 12px}.nav button{flex:1}h1{font-size:22px}}
</style></head><body>
<div id="message" class="message" hidden role="alert"></div>
<section id="login" class="card login"><h1>مدیریت Venzo</h1><p class="muted">ورود اختصاصی مدیر سرویس</p><form id="loginForm"><label>رمز مدیریت<input id="secret" type="password" autocomplete="current-password" required></label><label>کد شش‌رقمی برنامه احراز هویت<input id="otp" class="ltr" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="one-time-code" required></label><button class="primary" type="submit">ورود به پنل</button></form></section>
<main id="app" class="shell" hidden><header class="top"><div><h1>کنترل سرویس Venzo</h1><small>کیفیت اتصال، تنظیمات و ارتباط با کاربران</small></div><button id="logout">خروج</button></header><nav class="nav" aria-label="بخش‌های مدیریت"><button data-page="quality">کیفیت اتصال</button><button data-page="configs">کانفیگ و fallback</button><button data-page="announcements">اعلان‌ها</button><button data-page="security">امنیت</button></nav>
<section id="quality"><div class="row"><h2>کیفیت اتصال گزارش‌شده</h2><div class="tools"><select id="period" aria-label="بازه گزارش"><option value="7">۷ روز اخیر</option><option value="1">امروز</option><option value="30">۳۰ روز اخیر</option></select><button id="refreshQuality">به‌روزرسانی</button></div></div><p class="note">فقط دورهای بررسی خودکار/دستی پس از بالا آمدن هسته، با اجازه کاربر محاسبه می‌شوند؛ خطای راه‌اندازی هسته و همه تلاش‌های اتصال در این آمار نیستند. این آمار نماینده همه کاربران یا تست مستقل سرورها نیست. بازه روزها بر مبنای UTC است.</p><div id="metrics" class="grid section"></div><div class="card section"><h2>روند روزانه</h2><div id="days" class="list"></div></div><div class="split section"><div class="card"><h2>مسیرهای اتصال</h2><div id="transports" class="table"></div></div><div class="card"><h2>نسخه‌های برنامه</h2><div id="versions" class="table"></div></div></div><div class="card section"><h2>خطاهای ثبت‌شده</h2><div id="errors" class="table"></div></div><p id="opens" class="muted"></p><details class="card section"><summary>سوابق بازدید نسخه‌های قبلی</summary><p class="muted">شناسه‌ها متعلق به نصب برنامه‌اند، نه هویت اشخاص. این اطلاعات تاریخی با آمار کیفیت جدید ادغام نمی‌شود.</p><button id="loadLegacy">دریافت سوابق</button><p id="legacySummary"></p><div id="legacyVisitors" class="table"></div></details></section>
<section id="configs" hidden><div class="row"><h2>کانفیگ‌ها و مسیر جایگزین</h2><button id="reloadConfigs">بارگذاری مجدد</button></div><p class="note">ویرایش‌ها تا زدن «انتشار» فقط پیش‌نویس همین صفحه‌اند. اعتبار قالب به معنی اتصال موفق نیست. افزودن MASQUE/WARP به کانفیگ معتبر آن نیاز دارد و حساب Cloudflare ایجاد نمی‌کند.</p><div id="sources" class="section muted"></div><details class="card section"><summary>کانفیگ‌های منابع خودکار (فقط مشاهده)</summary><p class="muted">این فهرست جدا از گروه‌های دستی است و با تازه‌سازی منبع تغییر می‌کند.</p><button id="loadCatalog">دریافت فهرست فعلی</button><textarea id="catalogLines" class="ltr" readonly aria-label="کانفیگ‌های خودکار"></textarea><div id="catalogSources" class="table"></div></details><div class="split section"><form id="groupForm" class="card"><h2>ویرایش گروه</h2><label>نام گروه<input id="groupName" maxlength="80" required></label><label>نوع مسیر<select id="groupTransport"><option value="normal">سرور معمول</option><option value="masque">MASQUE</option><option value="warp">Cloudflare WARP</option><option value="wireguard">WireGuard</option></select></label><label>تاریخ انقضا (اختیاری، ساعت محلی)<input id="groupExpiry" type="datetime-local"></label><label>کانفیگ‌ها؛ هر خط یک مورد<textarea id="groupLines" class="ltr" spellcheck="false" required></textarea></label><label><span><input id="groupEnabled" type="checkbox" checked> فعال</span></label><div class="tools"><button type="submit">ثبت در پیش‌نویس</button><button type="button" id="resetGroup">گروه جدید</button></div></form><div class="card"><h2>گروه‌های پیش‌نویس</h2><div id="groups" class="list"></div></div></div><div class="card section"><h2>ترتیب fallback</h2><p class="muted">سرورهای معمول همیشه اول هستند. این تنظیم با نسخه جدید اندروید دریافت می‌شود.</p><label><span><input id="fallbackEnabled" type="checkbox" checked> استفاده از مسیرهای جایگزین</span></label><label>اولویت پس از سرور معمول<select id="fallbackOrder"><option value="masque,warp,wireguard">MASQUE ← WARP ← WireGuard</option><option value="warp,masque,wireguard">WARP ← MASQUE ← WireGuard</option><option value="wireguard,masque,warp">WireGuard ← MASQUE ← WARP</option><option value="masque,wireguard,warp">MASQUE ← WireGuard ← WARP</option><option value="warp,wireguard,masque">WARP ← WireGuard ← MASQUE</option><option value="wireguard,warp,masque">WireGuard ← WARP ← MASQUE</option></select></label><div class="tools"><button id="previewConfigs">بررسی تغییرات</button><button id="publishConfigs" class="primary" disabled>انتشار کانفیگ و تنظیمات</button></div><p id="previewResult" class="draft" role="status">هنوز بررسی نشده است.</p></div><div class="card section"><h2>بازگردانی تنظیمات</h2><div class="tools"><select id="history" aria-label="نسخه تنظیمات"></select><button id="restore" class="danger">بازگردانی نسخه انتخابی</button></div><p class="muted">۲۰ نسخه آخر نگهداری می‌شود؛ بازگردانی به‌صورت یک نسخه جدید منتشر خواهد شد.</p></div></section>
<section id="announcements" hidden><h2>مرکز اعلان‌ها</h2><p class="note">اعلان‌ها هنگام بررسی دوره‌ای برنامه دریافت می‌شوند؛ ارسال فوری تضمین نمی‌شود. زمان‌ها با ساعت محلی وارد می‌شوند. هر پیام تازه شناسه جدید می‌گیرد؛ ویرایش پیام قبلی الزاماً آن را دوباره نمایش نمی‌دهد.</p><div class="split section"><form id="announcementForm" class="card"><label>عنوان<input id="announcementTitle" maxlength="120" required></label><label>نوع<select id="announcementType"><option value="news">خبر</option><option value="discount">تخفیف</option><option value="update">آپدیت</option></select></label><label>متن<textarea id="announcementBody" maxlength="500" required></textarea></label><label>لینک HTTPS (اختیاری)<input id="announcementUrl" class="ltr" type="url"></label><label>شروع (خالی = اکنون)<input id="announcementStart" type="datetime-local"></label><label>پایان (اختیاری)<input id="announcementEnd" type="datetime-local"></label><label><span><input id="announcementEnabled" type="checkbox" checked> فعال</span></label><div class="tools"><button type="submit">ثبت و پیش‌نمایش</button><button type="button" id="resetAnnouncement">پیام جدید</button></div></form><div class="card"><h2>پیش‌نمایش پیام‌ها</h2><div id="announcementList" class="list"></div></div></div><div class="tools"><button id="saveAnnouncements" class="primary">انتشار تغییرات اعلان‌ها</button><button id="reloadAnnouncements">بارگذاری مجدد</button></div></section>
<section id="security" hidden><h2>امنیت مدیر</h2><div class="card section"><p>ورود با رمز مستقل و کد دومرحله‌ای؛ اعتبار نشست: ۴ ساعت.</p><p class="muted">کلیدهای API در این پنل نمایش داده نمی‌شوند. تغییر رمز یا بازیابی کد دومرحله‌ای از تنظیمات امن استقرار انجام می‌شود.</p><button id="revoke" class="danger">خروج از تمام نشست‌ها</button></div><div class="card"><h2>آخرین عملیات مدیر</h2><div id="audit" class="table"></div></div></section>
</main><script nonce="${nonce}">(() => {
// Wrangler's keepNames transform inserts __name calls inside serialized functions.
// Supply that helper in the page's own scope; the Worker scope is not serialized.
const __name = (fn, name) => Object.defineProperty(fn, 'name', { value: name, configurable: true });
(${ownerClient.toString()})();
})();</script></body></html>`, { headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'Referrer-Policy': 'no-referrer', 'Content-Security-Policy': `default-src 'none'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}'; connect-src 'self'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'` } });
}

function ownerClient() {
  const $ = id => document.getElementById(id), fa = n => Number(n || 0).toLocaleString('fa-IR');
  let announcementsLoaded = false;
  let documentState = null, preview = null, editingGroup = null, messages = { revision: 0, announcements: [] }, editingMessage = null, quality = [];
  const labels = { normal: 'معمول', masque: 'MASQUE', warp: 'WARP', wireguard: 'WireGuard', no_candidates: 'بدون سرور پاسخ‌گو', no_traffic: 'عدم عبور ترافیک', route_unverified: 'مسیر تأیید نشد', internal: 'خطای داخلی', cancelled: 'لغو کاربر', none: 'بدون خطا' };
  const errors = { INVALID_CREDENTIALS: 'رمز یا کد دومرحله‌ای نادرست است.', ADMIN_NOT_CONFIGURED: 'تنظیمات امنیتی پنل کامل نیست؛ مدیر باید تنظیمات استقرار را تکمیل کند.', OTP_ALREADY_USED: 'این کد استفاده شده؛ کد بعدی را وارد کنید.', TOO_MANY_ATTEMPTS: 'تلاش زیاد؛ ده دقیقه بعد امتحان کنید.', REVISION_CONFLICT: 'تنظیمات در نشست دیگری تغییر کرده؛ قبل از ادامه بارگذاری مجدد کنید.', PREVIEW_HAS_REJECTED_LINES: 'خطوط نامعتبر یا تکراری را اصلاح و دوباره بررسی کنید.', PREVIEW_REQUIRED: 'تغییرات را دوباره بررسی کنید.', SERVICE_UNAVAILABLE: 'سرویس موقتاً در دسترس نیست؛ اطلاعات فرم حفظ شده است.' };
  function notice(text, bad = false) { $('message').hidden = false; $('message').textContent = text; $('message').classList.toggle('bad', bad); }
  async function api(path, method = 'GET', body) {
    const r = await fetch(path.startsWith('/v1/') ? path : '/v1/internal/admin/' + path, { method, credentials: 'same-origin', cache: 'no-store', headers: { 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) });
    const data = await r.json();
    if (!r.ok) { if (r.status === 401 && path !== 'login') showLogin(); throw new Error(errors[data.error] || data.error || 'دریافت اطلاعات ناموفق بود.'); }
    return data;
  }
  function bind(id, event, fn) { $(id).addEventListener(event, async e => { e.preventDefault(); const button = e.submitter || (e.currentTarget.tagName === 'BUTTON' ? e.currentTarget : null); if (button) button.disabled = true; try { await fn(e); } catch (err) { notice(err.message, true); } finally { if (button) button.disabled = button.id === 'publishConfigs' && (!preview || !!(preview.diagnostics.invalid || preview.diagnostics.duplicates)); } }); }
  function node(tag, text, cls) { const el = document.createElement(tag); if (text !== undefined) el.textContent = text; if (cls) el.className = cls; return el; }
  function button(text, fn) { const b = node('button', text); b.type = 'button'; b.onclick = fn; return b; }
  function table(id, headers, rows) { const root = $(id); root.replaceChildren(); if (!rows.length) { root.append(node('p', 'هنوز داده‌ای ثبت نشده است.', 'empty')); return; } const t = node('table'), head = node('tr'); headers.forEach(h => head.append(node('th', h))); const thead = node('thead'); thead.append(head); t.append(thead); const body = node('tbody'); rows.forEach(row => { const tr = node('tr'); row.forEach(c => tr.append(node('td', c))); body.append(tr); }); t.append(body); root.append(t); }
  function showLogin() { $('app').hidden = true; $('login').hidden = false; documentState = null; preview = null; announcementsLoaded = false; messages = { revision: 0, announcements: [] }; quality = []; editingGroup = null; editingMessage = null; for (const id of ['groups', 'announcementList', 'audit', 'metrics', 'days', 'transports', 'versions', 'errors', 'legacyVisitors', 'catalogSources']) $(id).replaceChildren(); $('groupForm').reset(); $('announcementForm').reset(); $('catalogLines').value = ''; $('legacySummary').textContent = ''; }
  bind('loadCatalog', 'click', async () => {
    const data = await api('catalog');
    $('catalogLines').value = data.configs.join('\n');
    table('catalogSources', ['منبع', 'تعداد قالب معتبر'], data.sources.map(s => [s.name || s.id, fa(s.config_count)]));
    if (!data.configs.length) notice('فهرست خودکار هنوز در کش سرور موجود نیست.');
  });
  bind('loadLegacy', 'click', async () => {
    const data = await api('legacy-usage');
    $('legacySummary').textContent = 'اجراهای هفت روز اخیر در سامانه قدیمی: ' + fa(data.summary?.metrics?.opens_7d);
    table('legacyVisitors', ['شناسه نصب', 'نسخه', 'آخرین مشاهده', 'اجرا'], data.visitors.map(v => [v.install_id, v.app_version, new Date(v.last_seen_at).toLocaleString('fa-IR'), fa(v.open_count)]));
  });
  function localValue(n) { if (!n) return ''; const d = new Date(n); return new Date(n - d.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
  function timestamp(id) { return $(id).value ? new Date($(id).value).getTime() : 0; }
  async function page(id) { for (const x of ['quality', 'configs', 'announcements', 'security']) $(x).hidden = x !== id; document.querySelectorAll('[data-page]').forEach(b => b.classList.toggle('active', b.dataset.page === id)); if (id === 'quality') await loadQuality(); if (id === 'configs' && !documentState) await loadConfigs(); if (id === 'announcements' && !announcementsLoaded) await loadAnnouncements(); if (id === 'security') { const a = await api('audit'); table('audit', ['عملیات', 'زمان'], a.events.map(e => [e.event, new Date(e.at).toLocaleString('fa-IR')])); } }
  document.querySelectorAll('[data-page]').forEach(b => { b.onclick = () => page(b.dataset.page).catch(e => notice(e.message, true)); });
  async function enter() { $('login').hidden = true; $('app').hidden = false; await page('quality'); }
  bind('loginForm', 'submit', async () => { await api('login', 'POST', { secret: $('secret').value, otp: $('otp').value }); $('secret').value = ''; $('otp').value = ''; $('message').hidden = true; await enter(); });
  bind('logout', 'click', async () => { await api('logout', 'POST', {}); showLogin(); });
  bind('revoke', 'click', async () => { if (confirm('از تمام نشست‌ها، از جمله همین صفحه، خارج شوید؟')) { await api('revoke', 'POST', {}); showLogin(); } });
  async function loadQuality() { quality = (await api('quality')).days; renderQuality(); const o = await api('opens'); $('opens').textContent = 'اجراهای اختیاری گزارش‌شده در بازه نگهداری: ' + fa(o.days.reduce((s, d) => s + d.opens, 0)) + ' — با تعداد اشخاص یا اتصال موفق یکسان نیست.'; }
  function renderQuality() { const days = quality.slice(-Number($('period').value)); const totals = days.reduce((s, d) => { for (const key of ['attempts', 'success', 'failure', 'cancelled', 'success_duration_ms']) s[key] = (s[key] || 0) + (d[key] || 0); return s; }, {}); const completed = totals.success + totals.failure; $('metrics').replaceChildren(); for (const [label, value] of [['تلاش ثبت‌شده', fa(totals.attempts)], ['موفق از تلاش‌های پایان‌یافته', completed ? fa(Math.round(totals.success / completed * 100)) + '٪' : '—'], ['میانگین زمان بررسی موفق', totals.success ? fa(Math.round(totals.success_duration_ms / totals.success / 1000)) + ' ثانیه' : '—'], ['لغو توسط کاربر', fa(totals.cancelled)]]) { const c = node('article', undefined, 'card metric'); c.append(node('span', label), node('strong', value)); $('metrics').append(c); } $('days').replaceChildren(); days.forEach(d => { const line = node('div', undefined, 'barline'), meter = node('meter'); meter.min = 0; meter.max = Math.max(1, d.attempts); meter.value = d.success; meter.setAttribute('aria-label', 'اتصال موفق از تلاش‌های روز ' + d.date); line.append(node('small', d.date), meter, node('small', fa(d.success) + '/' + fa(d.attempts))); $('days').append(line); }); for (const field of ['transports', 'versions', 'errors']) { const buckets = {}; days.forEach(d => Object.entries(d[field] || {}).forEach(([name, b]) => { const t = buckets[name] ||= { attempts: 0, success: 0, failure: 0, cancelled: 0 }; for (const k of Object.keys(t)) t[k] += b[k] || 0; })); table(field, ['عنوان', 'تلاش', 'موفق', 'ناموفق', 'لغو'], Object.entries(buckets).map(([n, b]) => [labels[n] || n, fa(b.attempts), fa(b.success), fa(b.failure), fa(b.cancelled)])); } }
  bind('period', 'change', renderQuality); bind('refreshQuality', 'click', loadQuality);
  function dirty() { preview = null; $('publishConfigs').disabled = true; $('previewResult').textContent = 'پیش‌نویس تغییر کرده؛ دوباره بررسی کنید.'; }
  async function loadConfigs() { documentState = await api('configs'); $('fallbackEnabled').checked = documentState.policy.enabled; $('fallbackOrder').value = documentState.policy.order.slice(1).join(','); renderGroups(); dirty(); const h = await api('configs/history'); $('history').replaceChildren(...h.revisions.map(v => { const o = node('option', 'نسخه ' + fa(v)); o.value = v; return o; })); const legacyWarning = documentState.legacy_fallback ? 'کانفیگ‌های قدیمیِ بزرگ همچنان فعال و فقط‌خواندنی‌اند؛ انتشار گروه‌های دستی جدید جایگزین آن‌ها می‌شود. ' : ''; try { const s = await api('/v1/free/sources'); $('sources').textContent = legacyWarning + 'کانفیگ منابع خودکار: ' + fa(s.config_count) + ' — این عدد تأیید اتصال نیست.'; } catch { $('sources').textContent = legacyWarning + 'دریافت وضعیت منابع خودکار ممکن نشد؛ گروه‌های دستی در دسترس‌اند.'; } }
  function resetGroup() { editingGroup = null; $('groupForm').reset(); }
  function renderGroups() { $('groups').replaceChildren(); if (!documentState.groups.length) $('groups').append(node('p', 'هنوز گروهی اضافه نشده است.', 'empty')); documentState.groups.forEach(g => { const card = node('div', undefined, 'card'); card.append(node('strong', g.name), node('p', fa(g.configs.length) + ' کانفیگ · ' + (labels[g.transport] || 'معمول') + ' · ' + (g.enabled ? 'فعال' : 'غیرفعال'))); card.append(button('ویرایش', () => { editingGroup = g.id; $('groupName').value = g.name; $('groupTransport').value = g.transport || 'normal'; $('groupLines').value = g.configs.join('\n'); $('groupEnabled').checked = g.enabled; $('groupExpiry').value = localValue(g.expires_at); }), button(g.enabled ? 'غیرفعال کردن' : 'فعال کردن', () => { g.enabled = !g.enabled; dirty(); renderGroups(); }), button('حذف از پیش‌نویس', () => { if (confirm('گروه از پیش‌نویس حذف شود؟')) { documentState.groups = documentState.groups.filter(x => x.id !== g.id); dirty(); renderGroups(); } })); $('groups').append(card); }); }
  bind('groupForm', 'submit', () => { const g = { id: editingGroup || crypto.randomUUID(), name: $('groupName').value, transport: $('groupTransport').value, configs: $('groupLines').value.split(/\r?\n/), enabled: $('groupEnabled').checked, expires_at: timestamp('groupExpiry') }; const index = documentState.groups.findIndex(x => x.id === g.id); if (index < 0) documentState.groups.push(g); else documentState.groups[index] = g; resetGroup(); dirty(); renderGroups(); });
  bind('resetGroup', 'click', resetGroup); bind('reloadConfigs', 'click', async () => { if (confirm('پیش‌نویس ذخیره‌نشده کنار گذاشته شود؟')) await loadConfigs(); }); bind('fallbackOrder', 'change', dirty); bind('fallbackEnabled', 'change', dirty);
  bind('previewConfigs', 'click', async () => { documentState.policy = { enabled: $('fallbackEnabled').checked, order: ['normal', ...$('fallbackOrder').value.split(',')] }; preview = await api('configs/preview', 'POST', documentState); const d = preview.diagnostics; $('previewResult').textContent = `معتبر: ${fa(d.valid)} | نامعتبر: ${fa(d.invalid)} | تکراری: ${fa(d.duplicates)} | افزوده: ${fa(preview.diff.added)} | حذف: ${fa(preview.diff.removed)}`; $('publishConfigs').disabled = !!(d.invalid || d.duplicates); });
  bind('publishConfigs', 'click', async () => { if (!preview || !confirm('این تنظیمات برای کاربران منتشر شود؟')) return; await api('configs/publish', 'POST', { ...documentState, fingerprint: preview.fingerprint }); await loadConfigs(); notice('کانفیگ‌ها و ترتیب fallback منتشر شدند.'); });
  bind('restore', 'click', async () => { if (confirm('نسخه انتخابی جایگزین تنظیمات فعلی شود؟')) { await api('configs/restore', 'POST', { revision: documentState.revision, target: Number($('history').value) }); await loadConfigs(); notice('تنظیمات بازگردانی شدند.'); } });
  async function loadAnnouncements() { messages = await api('announcements'); announcementsLoaded = true; renderAnnouncements(); }
  function renderAnnouncements() { $('announcementList').replaceChildren(); messages.announcements.forEach(a => { const c = node('article', undefined, 'card'); c.append(node('strong', a.title), node('p', a.body), node('small', (a.enabled ? 'فعال' : 'غیرفعال') + ' · شروع: ' + (a.starts_at ? new Date(a.starts_at).toLocaleString('fa-IR') : 'اکنون'))); if (a.action_url) c.append(node('p', a.action_url, 'ltr')); c.append(button('ویرایش', () => { editingMessage = a.id; $('announcementTitle').value = a.title; $('announcementBody').value = a.body; $('announcementType').value = a.type; $('announcementUrl').value = a.action_url || ''; $('announcementStart').value = localValue(a.starts_at); $('announcementEnd').value = localValue(a.expires_at); $('announcementEnabled').checked = a.enabled !== false; }), button('حذف از پیش‌نویس', () => { messages.announcements = messages.announcements.filter(x => x.id !== a.id); renderAnnouncements(); })); $('announcementList').append(c); }); }
  bind('announcementForm', 'submit', () => { const a = { id: editingMessage || crypto.randomUUID(), title: $('announcementTitle').value, body: $('announcementBody').value, type: $('announcementType').value, action_url: $('announcementUrl').value || null, starts_at: timestamp('announcementStart'), expires_at: timestamp('announcementEnd'), enabled: $('announcementEnabled').checked }; const i = messages.announcements.findIndex(x => x.id === a.id); if (i < 0) messages.announcements.push(a); else messages.announcements[i] = a; editingMessage = null; $('announcementForm').reset(); renderAnnouncements(); });
  bind('resetAnnouncement', 'click', () => { editingMessage = null; $('announcementForm').reset(); }); bind('reloadAnnouncements', 'click', async () => { if (confirm('پیش‌نویس کنار گذاشته شود؟')) await loadAnnouncements(); }); bind('saveAnnouncements', 'click', async () => { if (confirm('اعلان‌های پیش‌نمایش منتشر شوند؟')) { messages = await api('announcements', 'PUT', messages); renderAnnouncements(); notice('اعلان‌ها ذخیره شدند.'); } });
  api('session').then(enter).catch(e => { showLogin(); if (!String(e.message).includes('LOGIN_REQUIRED')) notice(e.message, true); });
}
